%% ERP_Analysis_BA_Saume

% Verfasst von Thomas Saume, MSH Medical School Hamburg,
% thomas.saume@student.medichalschool-hamburg.de

% Analyse-Schritte:
% 1. Vorbereitung
% 2. Grand Average bilden
% 3. Neue Bins definieren
% 4. Bin-Operations für die N2pc: Kontra minus ipsi (und lteralisierte P1)
% 5. Mean Amplitudes berechnen

%% 1. Vorbereitung
clearvars
eeglab nogui % EEGLAB starten
clear ALLERP

% Pfad zum Ornder mit den fertig vorverarbeiteten ERP-Sets
% also "Prob1_erp_filt.erp", "Prob2_erp_filt.erp", "Prob3_erp_filt.erp"...
path_to_erp_sets = 'F:\path\to\erpsets'; 
cd(path_to_erp_sets);

% list sei ein Array mit allen gefilterten ERP-Sets aus dem Preprocessing
list = dir('*filt.erp*');
filenames = {list.name};

%% 2. Grand Average bilden
% ERP-Sets aller Probanden laden
[ERP ALLERP] = pop_loaderp('filename', filenames, 'filepath', path_to_erp_sets); 
% Grand Average berechnen und speichern
DQ_spec_structure = struct();
ERP_GR_AVG = pop_gaverager(ALLERP , 'DQ_flag', 1, 'DQ_spec', DQ_spec_structure,...
    'Erpsets', [1:length(filenames)], 'ExcludeNullBin', 'on', 'SEM', 'on');
ERP = pop_savemyerp(ERP_GR_AVG, 'erpname', 'Group_ERP', 'filename',...
    'Group_ERP.erp', 'filepath', path_to_erp_sets, 'Warning', 'on'); % Speichern

%% 3. Neue Bins definieren
% Das ist eine Variable, in der die neuen Bins für die Analyse definiert und der
% Rechenweg spezifiziert wird.
neue_bins = {'b17 = (b1+b2+b7+b8+b9+b10+b15+b16)/8 label all_con',...% CON vs. INC
    'b18 = (b3+b4+b5+b6+b11+b12+b13+b14)/8 label all_inc',...
    'b19 = (b1+b3+b5+b7+b9+b11+b13+b15)/8 label left',... % LEFT vs. RIGHT
    'b20 = (b2+b4+b6+b8+b10+b12+b14+b16)/8 label right',...
    'b21 = (b1+b2+b3+b4+b5+b6+b7+b8)/8 label self',... % SELBST vs. FREMD
    'b22 = (b9+b10+b11+b12+b13+b14+b15+b16)/8 label other',...
    'b23 = (b1+b2+b3+b4+b9+b10+b11+b12)/8 label pos_satz',... % POS vs. NEG Satz
    'b24 = (b5+b6+b7+b8+b13+b14+b15+b16)/8 label neg_satz',...
    'b25 = (b1+b2+b5+b6+b9+b10+b13+b14)/8 label hap_emoji',... % HAP vs. ANG Emoji
    'b26 = (b3+b4+b7+b8+b11+b12+b15+b16)/8 label ang_emoji',...
    'b27 = (b1+b5+b9+b13)/4 label hap_emoji_li',... % Für N2pc Haupteffekt Emoji
    'b28 = (b2+b6+b10+b14)/4 label hap_emoji_re',...
    'b29 = (b3+b7+b11+b15)/4 label ang_emoji_li',...
    'b30 = (b4+b8+b12+b16)/4 label ang_emoji_re',...
    'b31 = (b1+b7+b9+b15)/4 label con_li',... % Für N2pc Haupteffekt Kongruenz
    'b32 = (b2+b8+b10+b16)/4 label con_re',...
    'b33 = (b3+b5+b11+b13)/4 label inc_li',...
    'b34 = (b4+b6+b12+b14)/4 label inc_re'...
    'b35 = (b1+b3+b5+b7)/4 label self_li',... % Für N2pc Haupteffekt Referenz
    'b36 = (b2+b4+b6+b8)/4 label self_re',...
    'b37 = (b9+b11+b13+b15)/4 label other_li',...
    'b38 = (b10+b12+b14+b16)/4 label other_re',...
    'b39 = (b1+b9)/2 label hap_emoji_con_li',... % Für N2pc Interaktion EMO x KON
    'b40 = (b2+b10)/2 label hap_emoji_con_re',...
    'b41 = (b7+15)/2 label ang_emoji_con_li',...
    'b42 = (b8+b16)/2 label ang_emoji_con_re',...
    'b43 = (b5+b13)/2 label hap_emoji_inc_li',...
    'b44 = (b6+b14)/2 label hap_emoji_inc_re',...
    'b45 = (b3+b11)/2 label ang_emoji_inc_li',...
    'b46 = (b4+b12)/2 label ang_emoji_inc_re',...
    'b47 = (b1+b5)/2 label self_hap_emoji_li',... % Für N2pc Interaktion BEZ x EMO
    'b48 = (b2+b6)/2 label self_hap_emoji_re',...
    'b49 = (b9+b13)/2 label other_hap_emoji_li',...
    'b50 = (b10+b14)/2 label other_hap_emoji_re',...
    'b51 = (b3+b7)/2 label self_ang_emoji_li',...
    'b52 = (b4+b8)/2 label self_ang_emoji_re',...
    'b53 = (b11+b15)/2 label other_ang_emoji_li',...
    'b54 = (b12+b16)/2 label other_ang_emoji_re'};

%% 4. Bin-Operations für die N2pc: Kontralateral minus ipsilateral

clear *ERP*
% Da die folgenden Bin-Operations (also die Berechnung der N2pc durch Kontra-Ipsi)
% für ALLE Probanden einzeln sowie auch für den Grand Average (zwecks Plotting)
% erfolgen soll, wird hier nun zu unserer list der Grand Average hinzugefügt
list = [list; dir('Group_ERP.erp')];
for sub = 1:length(list)
    subname = list(sub).name;
    %ERP-Set jedes Probanden laden
    ERP = pop_loaderp( 'filename', subname, 'filepath', path_to_erp_sets);

    % Die neuen Bins werden in das ERP-Set eingeladen
    ERP = pop_binoperator(ERP, neue_bins);

    % Speichern
    erpname_all_bins = [extractBefore(subname, '.') '_all_bins'];
    filename_all_bins = [erpname_all_bins '.erp'];
    ERP = pop_savemyerp(ERP, 'erpname', erpname_all_bins, 'filename', filename_all_bins, 'filepath', path_to_erp_sets, 'Warning', 'on');

    % Erstelle Contra & Ipsi für die N2pc. Also die kontralaterale und
    % ipsilaterale Aktivität für jede einzelne Bedingung 
    ERP_CI = pop_binoperator(ERP,{'prepareContraIpsi', ...
        'Lch = [ 1 3:5 7 6 8:10 12 11 14:16 2 13 17 24]',... % Linke/Rechte Kanäle
        'Rch = [ 32 30 31 27 29 28 25 26 21 23 22 19 20 18 2 13 17 24]',...
        'nbin1 = 0.5*bin19@Rch + 0.5*bin20@Lch label Links_Rechts Contra',... %L/R
        'nbin2 = 0.5*bin19@Lch + 0.5*bin20@Rch label Links_Rechts Ipsi',...
        'nbin3 = 0.5*bin27@Rch + 0.5*bin28@Lch label lr_hap_emoji Contra',... %EMO
        'nbin4 = 0.5*bin27@Lch + 0.5*bin28@Rch label lr_hap_emoji Ipsi',...
        'nbin5 = 0.5*bin29@Rch + 0.5*bin30@Lch label lr_ang_emoji Contra',...
        'nbin6 = 0.5*bin29@Lch + 0.5*bin30@Rch label lr_ang_emoji Ipsi',...
        'nbin7 = 0.5*bin31@Rch + 0.5*bin32@Lch label lr_con Contra',... %CON
        'nbin8 = 0.5*bin31@Lch + 0.5*bin32@Rch label lr_con Ipsi',...
        'nbin9 = 0.5*bin33@Rch + 0.5*bin34@Lch label lr_inc Contra',...
        'nbin10 = 0.5*bin33@Lch + 0.5*bin34@Rch label lr_inc Ipsi',...
        'nbin11 = 0.5*bin35@Rch + 0.5*bin36@Lch label lr_self Contra',... % BEZUG
        'nbin12 = 0.5*bin35@Lch + 0.5*bin36@Rch label lr_self Ipsi',...
        'nbin13 = 0.5*bin37@Rch + 0.5*bin38@Lch label lr_other Contra',...
        'nbin14 = 0.5*bin37@Lch + 0.5*bin38@Rch label lr_other Ipsi',...
        'nbin15 = 0.5*bin39@Rch + 0.5*bin40@Lch label lr_hap_emoji_con Contra',... % Kongruenz x Emoji Kontra & Ipsi
        'nbin16 = 0.5*bin39@Lch + 0.5*bin40@Rch label lr_hap_emoji_con Ipsi',...
        'nbin17 = 0.5*bin41@Rch + 0.5*bin42@Lch label lr_ang_emoji_con Contra',...
        'nbin18 = 0.5*bin41@Lch + 0.5*bin42@Rch label lr_ang_emoji_con Ipsi',...
        'nbin19 = 0.5*bin43@Rch + 0.5*bin44@Lch label lr_hap_emoji_inc Contra',...
        'nbin20 = 0.5*bin43@Lch + 0.5*bin44@Rch label lr_hap_emoji_inc Ipsi',...
        'nbin21 = 0.5*bin45@Rch + 0.5*bin46@Lch label lr_ang_emoji_inc Contra',...
        'nbin22 = 0.5*bin45@Lch + 0.5*bin46@Rch label lr_ang_emoji_inc Ipsi',...
        'nbin23 = 0.5*bin47@Rch + 0.5*bin48@Lch label lr_self_hap_emoji Contra',... % Referenz x Emoji Kontra & Ipsi
        'nbin24 = 0.5*bin47@Lch + 0.5*bin48@Rch label lr_self_hap_emoji Ipsi',...
        'nbin25 = 0.5*bin49@Rch + 0.5*bin50@Lch label lr_other_hap_emoji Contra',...
        'nbin26 = 0.5*bin49@Lch + 0.5*bin50@Rch label lr_other_hap_emoji Ipsi',...
        'nbin27 = 0.5*bin51@Rch + 0.5*bin52@Lch label lr_self_ang_emoji Contra',...
        'nbin28 = 0.5*bin51@Lch + 0.5*bin52@Rch label lr_self_ang_emoji Ipsi',...
        'nbin29 = 0.5*bin53@Rch + 0.5*bin54@Lch label lr_other_ang_emoji Contra',...
        'nbin30 = 0.5*bin53@Lch + 0.5*bin54@Rch label lr_other_ang_emoji Ipsi',...
        'nbin31 = 0.5*bin1@Rch + 0.5*bin2@Lch label lr_self_pos_hap Contra',... % Referenz x Valenz Prime x Valenz Emoji
        'nbin32 = 0.5*bin1@Lch + 0.5*bin2@Rch label lr_self_pos_hap Ipsi',...
        'nbin33 = 0.5*bin3@Rch + 0.5*bin4@Lch label lr_self_pos_ang Contra',...
        'nbin34 = 0.5*bin3@Lch + 0.5*bin4@Rch label lr_self_pos_ang Ipsi',...
        'nbin35 = 0.5*bin5@Rch + 0.5*bin6@Lch label lr_self_neg_hap Contra',...
        'nbin36 = 0.5*bin5@Lch + 0.5*bin6@Rch label lr_self_neg_hap Ipsi',...
        'nbin37 = 0.5*bin7@Rch + 0.5*bin8@Lch label lr_self_neg_ang Contra',...
        'nbin38 = 0.5*bin7@Lch + 0.5*bin8@Rch label lr_self_neg_ang Ipsi',...
        'nbin39 = 0.5*bin9@Rch + 0.5*bin10@Lch label lr_other_pos_hap Contra',...
        'nbin40 = 0.5*bin9@Lch + 0.5*bin10@Rch label lr_other_pos_hap Ipsi',...
        'nbin41 = 0.5*bin11@Rch + 0.5*bin12@Lch label lr_other_pos_ang Contra',...
        'nbin42 = 0.5*bin11@Lch + 0.5*bin12@Rch label lr_other_pos_ang Ipsi',...
        'nbin43 = 0.5*bin13@Rch + 0.5*bin14@Lch label lr_other_neg_hap Contra',...
        'nbin44 = 0.5*bin13@Lch + 0.5*bin14@Rch label lr_other_neg_hap Ipsi',...
        'nbin45 = 0.5*bin15@Rch + 0.5*bin16@Lch label lr_other_neg_ang Contra',...
        'nbin46 = 0.5*bin15@Lch + 0.5*bin16@Rch label lr_other_neg_ang Ipsi'});

    % Berechne Kontra minus Ipsi ("CI")
    % in der folgenden Reihenfolgen werden hier die N2pc's berechnet:
        % Gesamt N2pc, Haupteffekt Emoji, Haupteffekt Kongruenz,
        % Haupteffekt Bezug, Interaktionseffekt Kongruenz x Emotion, 
        % Interaktionseffekt Referenz vs. Emotion, dreifache Interaktion
    ERP_CI = pop_binoperator(ERP_CI,...
        {'bin47 = bin1 - bin2 label Links_Rechts Contra-Ipsi',... 
        'bin48 = bin3 - bin4 label lr_hap_emoji Contra-Ipsi',... 
        'bin49 = bin5 - bin6 label lr_ang_emoji Contra-Ipsi',...
        'bin50 = bin7 - bin8 label lr_con Contra-Ipsi',... 
        'bin51 = bin9 - bin10 label lr_inc Contra-Ipsi',...
        'bin52 = bin11 - bin12 label lr_self Contra-Ipsi',... 
        'bin53 = bin13 - bin14 label lr_other Contra-Ipsi',...
        'bin54 = bin15 - bin16 label lr_hap_emoji_con Contra-Ipsi',... 
        'bin55 = bin17 - bin18 label lr_ang_emoji_con Contra-Ipsi',...
        'bin56 = bin19 - bin20 label lr_hap_emoji_inc Contra-Ipsi',...
        'bin57 = bin21 - bin22 label lr_ang_emoji_inc Contra-Ipsi',...
        'bin58 = bin23 - bin24 label lr_self_hap_emoji Contra-Ipsi',... 
        'bin59 = bin25 - bin26 label lr_other_hap_emoji Contra-Ipsi',...
        'bin60 = bin27 - bin28 label lr_self_ang_emoji Contra-Ipsi',...
        'bin61 = bin29 - bin30 label lr_other_ang_emoji Contra-Ipsi',...
        'bin62 = bin31 - bin32 label lr_self_pos_hap Contra-Ipsi',... 
        'bin63 = bin33 - bin34 label lr_self_pos_ang Contra-Ipsi',...
        'bin64 = bin35 - bin36 label lr_self_neg_hap Contra-Ipsi',...
        'bin65 = bin37 - bin38 label lr_self_neg_ang Contra-Ipsi',...
        'bin66 = bin39 - bin40 label lr_other_pos_hap Contra-Ipsi',...
        'bin67 = bin41 - bin42 label lr_other_pos_ang Contra-Ipsi',...
        'bin68 = bin43 - bin44 label lr_other_neg_hap Contra-Ipsi',...
        'bin69 = bin45 - bin46 label lr_other_neg_ang Contra-Ipsi'});

    % Speichern
    erpname_ci = [extractBefore(subname, '.') '_ci'];
    filename_ci = [erpname_ci '.erp'];
    ERP_CI = pop_savemyerp(ERP_CI, 'erpname', erpname_ci, ...
        'filename', filename_ci, 'filepath', path_to_erp_sets, 'Warning', 'on');
    clear *ERP*
end

%% 5. Mean Amplitudes berechnen
% Alle CI-ERP-Sets einladen
all_ci_list = dir('*filt_ci.erp*');
all_ci_filenames = {all_ci_list.name};
[ERP ALLERP] = pop_loaderp('filename', all_ci_filenames, 'filepath', path_to_erp_sets);

% Mean Amplitudes berechnen N2pc
time_of_interest_n2pc = [260 300];
bins_of_interest_n2pc = [47:69];
channel_of_interest_n2pc = 15; % -> P7/P8
mean_amplitude_filename_n2pc = 'EARLY_MeanAmp_N2pc_lat_180ms_220ms_P7vsP8.txt';
ALLERP = pop_geterpvalues(ALLERP, time_of_interest_n2pc, bins_of_interest_n2pc, channel_of_interest_n2pc, 'Baseline', 'pre', 'Erpsets', 1:length(all_ci_filenames), 'FileFormat', 'wide', 'Filename', mean_amplitude_filename_n2pc, 'Fracreplace', 'NaN', 'InterpFactor',1, 'Measure', 'meanbl', 'PeakOnset',1, 'Resolution',3 );

% Mean Amplitudes berechnen lateralisierte P1
time_of_interest_p1 = [110 160];
bins_of_interest_lat_p1 = [52:53];
channel_of_interest_lateralized_p1 = 15; % -> P7/P8
mean_amplitude_filename_lateralized_p1 = 'MeanAmp_P1_lat_110ms_160ms_P7vsP8.txt';
ALLERP = pop_geterpvalues(ALLERP, time_of_interest_p1, bins_of_interest_lat_p1, channel_of_interest_lateralized_p1, 'Baseline', 'pre', 'Erpsets', 1:length(all_ci_filenames), 'FileFormat', 'wide', 'Filename', mean_amplitude_filename_lateralized_p1, 'Fracreplace', 'NaN', 'InterpFactor',1, 'Measure', 'meanbl', 'PeakOnset',1, 'Resolution',3 );